"""add username and is_system_user fields

Revision ID: 52bdba5bb348
Revises: ec93dbbc703f
Create Date: 2025-06-05 15:40:59.475771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bdba5bb348'
down_revision: Union[str, None] = 'ec93dbbc703f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system_user', sa.Boolean(), nullable=True, comment='是否为系统用户'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='用户名')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='用户名')
    op.drop_column('users', 'is_system_user')
    # ### end Alembic commands ###
