"""add current_jti to user

Revision ID: ec93dbbc703f
Revises: e84453a52dc8
Create Date: 2025-05-29 22:32:18.074174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec93dbbc703f'
down_revision: Union[str, None] = 'e84453a52dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_jti', sa.String(length=36), nullable=True, comment='当前有效JWT的jti'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_jti')
    # ### end Alembic commands ###
